### ISSUE TITLE
请问会加入删除隧道的功能吗？

### ISSUE THREAD

**Issue by nightingalegaze** [DDCHlsq/GostScript#1]
如题，有时候nat手抖写错端口，有没有可能加入删除功能。

**Comment by DDCHlsq** [comment]
脚本里选择“查看正在运行的gost进程”后，会显示相应进程及其进程号（pid），例如pid是666，只要在Linux 命令行里输入kill 666即可杀死该进程。

P.S. 真的没想到居然有人在我这个下面提issue😂，要是有别的想法（比如支持udp），我还是可以给你做一下的。

**Comment by nightingalegaze** [comment]
好的，谢谢，我刚接触这些，好多东西都是看着视频跟着做的。目前隧道是重启就失效了吗，我今天试了一个油管的重启不失效的教程结果重启了隧道还是塌了，也不知道是哪里的问题。，想问问有没有可能实现重启隧道不失效，没有的话也不要紧。

**Comment by DDCHlsq** [comment]
可以实现重启不失效的。
1. 设置开机自启动，例如centos可以把命令敲在/etc/rc.d/rc.local里，开机会自动执行（要先chmod +x rc.local赋予执行权限）
2. 设置systemd守护进程

**Comment by nightingalegaze** [comment]
谢谢，我有空试试。
